spring:
  datasource:
    password: root
    username: root
    url: jdbc:mysql://192.168.59.128:3306/gulimall_ums
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto  # 设置主键自增
server:
  port: 8000